# Generated by Django 5.2.17 on 2026-09-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(db_index=True, max_length=40)),
                (
                    "game_type",
                    models.CharField(
                        choices=[
                            ("sentence", "Составь предложение"),
                            ("pairs", "Пары слов"),
                            ("flashcard", "Карточки"),
                            ("letters", "Буквы"),
                        ],
                        max_length=20,
                    ),
                ),
                ("score", models.PositiveIntegerField(default=0)),
                ("max_score", models.PositiveIntegerField(default=0)),
                ("played_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-played_at"],
            },
        ),
        migrations.CreateModel(
            name="Sentence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ka",
                    models.CharField(
                        max_length=300, verbose_name="Грузинское предложение"
                    ),
                ),
                ("ru", models.CharField(max_length=300, verbose_name="Перевод")),
                (
                    "transcription",
                    models.CharField(max_length=300, verbose_name="Транскрипция"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ka",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Грузинское слово"
                    ),
                ),
                (
                    "transcription",
                    models.CharField(max_length=200, verbose_name="Транскрипция"),
                ),
                ("ru", models.CharField(max_length=300, verbose_name="Перевод")),
                ("pos", models.CharField(max_length=20, verbose_name="Часть речи")),
                (
                    "theme",
                    models.CharField(db_index=True, max_length=50, verbose_name="Тема"),
                ),
                (
                    "emoji",
                    models.CharField(
                        blank=True, default="", max_length=16, verbose_name="Эмодзи"
                    ),
                ),
            ],
            options={
                "ordering": ["ka"],
            },
        ),
    ]
